services:
  - type: web
    name: mutual-funds-api
    plan: free
    env: docker
    envVars:
      - key: RAG_DATABASE_PATH
        value: /app/data/rag.db
      - key: GROQ_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false
      - key: CHROMA_API_KEY
        sync: false
