services:
  - type: web
    name: mutual-funds-api
    env: docker
    envVars:
      - key: RAG_DATABASE_PATH
        value: /var/lib/data/rag.db
      - key: GROQ_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false
      - key: CHROMA_API_KEY
        sync: false
    disk:
      name: rag-storage
      mountPath: /var/lib/data
      sizeGB: 1
